namespace Application.AIML
{
    public static class UserDataGenerator
    {
        public static List<UserData> GetUsers() 
        {
            return new List<UserData>
            {
                new ()
                {
                    age=20,
                    gender="female",
                    weight=60.7f,
                    bloodPressure=130,
                    cholesterolLevel=55,
                    physicalActivityLevel=1,
                    smokingStatus=1f,
                    stressLevel=2,
                    risk=7.99f
                },
                new ()
                {
                    age = 25,
                    gender = "female",
                    weight = 68.4f,
                    bloodPressure = 120,
                    cholesterolLevel = 50,
                    physicalActivityLevel = 3,
                    smokingStatus = 0f,
                    stressLevel = 1,
                    risk = 5.10f
                },
                new ()
                {
                    age = 40,
                    gender = "male",
                    weight = 85.2f,
                    bloodPressure = 145,
                    cholesterolLevel = 200,
                    physicalActivityLevel = 2,
                    smokingStatus = 1f,
                    stressLevel = 4,
                    risk = 8.75f
                },
                new ()
                {
                    age = 35,
                    gender = "female",
                    weight = 72.5f,
                    bloodPressure = 130,
                    cholesterolLevel = 160,
                    physicalActivityLevel = 1,
                    smokingStatus = 1f,
                    stressLevel = 3,
                    risk = 7.40f
                },
                new ()
                {
                    age = 28,
                    gender = "male",
                    weight = 78.3f,
                    bloodPressure = 125,
                    cholesterolLevel = 180,
                    physicalActivityLevel = 4,
                    smokingStatus = 0f,
                    stressLevel = 2,
                    risk = 6.20f
                },
                new ()
                {
                    age = 50,
                    gender = "female",
                    weight = 95.6f,
                    bloodPressure = 160,
                    cholesterolLevel = 220,
                    physicalActivityLevel = 1,
                    smokingStatus = 1f,
                    stressLevel = 5,
                    risk = 9.50f
                },
                new ()
                {
                    age = 60,
                    gender = "male",
                    weight = 88.9f,
                    bloodPressure = 155,
                    cholesterolLevel = 210,
                    physicalActivityLevel = 2,
                    smokingStatus = 0f,
                    stressLevel = 4,
                    risk = 8.30f
                },
                new ()
                {
                    age = 45,
                    gender = "female",
                    weight = 80.1f,
                    bloodPressure = 140,
                    cholesterolLevel = 190,
                    physicalActivityLevel = 3,
                    smokingStatus = 0f,
                    stressLevel = 3,
                    risk = 7.80f
                },

                new () { age = 22, gender = "female", weight = 55.3f, bloodPressure = 120, cholesterolLevel = 140, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 1, risk = 4.30f },
                new () { age = 35, gender = "male", weight = 88.4f, bloodPressure = 145, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 7.00f },
                new () { age = 27, gender = "female", weight = 63.8f, bloodPressure = 115, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 5.00f },
                new () { age = 40, gender = "male", weight = 92.1f, bloodPressure = 160, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 9.10f },
                new () { age = 50, gender = "female", weight = 77.3f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 5, risk = 8.50f },
                new () { age = 28, gender = "male", weight = 82.5f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.20f },
                new () { age = 60, gender = "female", weight = 90.2f, bloodPressure = 155, cholesterolLevel = 230, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 3, risk = 8.70f },
                new () { age = 45, gender = "male", weight = 76.1f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 5.30f },
                new () { age = 33, gender = "female", weight = 69.8f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.80f },
                new () { age = 48, gender = "male", weight = 94.5f, bloodPressure = 160, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 9.60f },
                new () { age = 26, gender = "female", weight = 61.2f, bloodPressure = 125, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.80f },
                new () { age = 52, gender = "male", weight = 79.0f, bloodPressure = 138, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 8.20f },
                new () { age = 29, gender = "female", weight = 58.7f, bloodPressure = 118, cholesterolLevel = 140, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 4.50f },
                new () { age = 42, gender = "male", weight = 85.3f, bloodPressure = 148, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 7.10f },
                new () { age = 36, gender = "female", weight = 72.9f, bloodPressure = 130, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 2, risk = 6.80f },
                new () { age = 60, gender = "male", weight = 95.6f, bloodPressure = 170, cholesterolLevel = 250, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 9.90f },
                new () { age = 55, gender = "female", weight = 78.2f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 8.40f },
                new () { age = 47, gender = "male", weight = 91.7f, bloodPressure = 150, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 7.60f },
                new () { age = 30, gender = "female", weight = 65.3f, bloodPressure = 122, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 5.10f },
                new () { age = 39, gender = "male", weight = 80.4f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.80f },
                new () { age = 23, gender = "female", weight = 56.8f, bloodPressure = 118, cholesterolLevel = 140, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.20f },
                new () { age = 38, gender = "male", weight = 79.6f, bloodPressure = 145, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 7.40f },
                new () { age = 32, gender = "female", weight = 67.5f, bloodPressure = 125, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.60f },
                new () { age = 53, gender = "male", weight = 88.3f, bloodPressure = 155, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.90f },
                new () { age = 41, gender = "female", weight = 74.4f, bloodPressure = 138, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.20f },
                new () { age = 44, gender = "male", weight = 90.2f, bloodPressure = 150, cholesterolLevel = 200, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 7.80f },
                new () { age = 28, gender = "female", weight = 62.3f, bloodPressure = 120, cholesterolLevel = 145, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.10f },
                new () { age = 29, gender = "male", weight = 77.8f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 6.60f },
                new () { age = 61, gender = "female", weight = 92.5f, bloodPressure = 160, cholesterolLevel = 240, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 9.80f },
                new () { age = 24, gender = "male", weight = 70.2f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 5.20f },
                new () { age = 51, gender = "female", weight = 80.8f, bloodPressure = 145, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.90f },
                new () { age = 59, gender = "male", weight = 85.4f, bloodPressure = 150, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 8.60f },
                new () { age = 50, gender = "female", weight = 77.9f, bloodPressure = 140, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 7.50f },
                new () { age = 34, gender = "male", weight = 81.3f, bloodPressure = 125, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.10f },
                new () { age = 31, gender = "female", weight = 65.0f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 5.00f },
                new () { age = 46, gender = "male", weight = 95.8f, bloodPressure = 160, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 9.40f },
                new () { age = 39, gender = "female", weight = 70.9f, bloodPressure = 135, cholesterolLevel = 185, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.50f },
                new () { age = 42, gender = "male", weight = 89.2f, bloodPressure = 150, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.70f },
                new () { age = 57, gender = "female", weight = 92.7f, bloodPressure = 160, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 9.70f },
                new () { age = 33, gender = "male", weight = 78.6f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.80f },
                new () { age = 30, gender = "female", weight = 65.2f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.40f },
                new () { age = 56, gender = "male", weight = 92.0f, bloodPressure = 150, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 8.90f },
                new () { age = 37, gender = "female", weight = 73.3f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 7.20f },
                new () { age = 61, gender = "male", weight = 94.2f, bloodPressure = 160, cholesterolLevel = 230, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 9.80f },
                new () { age = 43, gender = "female", weight = 76.8f, bloodPressure = 130, cholesterolLevel = 160, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.90f },

                new () { age = 24, gender = "female", weight = 58.4f, bloodPressure = 118, cholesterolLevel = 140, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.10f },
                new () { age = 32, gender = "male", weight = 79.1f, bloodPressure = 130, cholesterolLevel = 165, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.60f },
                new () { age = 45, gender = "female", weight = 81.2f, bloodPressure = 135, cholesterolLevel = 185, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.40f },
                new () { age = 39, gender = "male", weight = 85.6f, bloodPressure = 140, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.90f },
                new () { age = 28, gender = "female", weight = 63.7f, bloodPressure = 125, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 5.10f },
                new () { age = 51, gender = "male", weight = 88.9f, bloodPressure = 160, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.90f },
                new () { age = 56, gender = "female", weight = 77.5f, bloodPressure = 145, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 8.30f },
                new () { age = 40, gender = "male", weight = 84.0f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.40f },
                new () { age = 29, gender = "female", weight = 62.1f, bloodPressure = 120, cholesterolLevel = 145, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.80f },
                new () { age = 36, gender = "male", weight = 90.3f, bloodPressure = 155, cholesterolLevel = 220, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.80f },
                new () { age = 50, gender = "female", weight = 76.9f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.60f },
                new () { age = 60, gender = "male", weight = 92.8f, bloodPressure = 160, cholesterolLevel = 240, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 9.90f },
                new () { age = 41, gender = "female", weight = 75.6f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.90f },
                new () { age = 44, gender = "male", weight = 83.3f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 6.70f },
                new () { age = 53, gender = "female", weight = 79.4f, bloodPressure = 145, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 8.40f },
                new () { age = 58, gender = "male", weight = 87.6f, bloodPressure = 150, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 5, risk = 8.80f },
                new () { age = 38, gender = "female", weight = 71.0f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.30f },
                new () { age = 54, gender = "male", weight = 90.9f, bloodPressure = 155, cholesterolLevel = 230, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 9.10f },
                new () { age = 62, gender = "female", weight = 95.0f, bloodPressure = 160, cholesterolLevel = 240, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 9.60f },
                new () { age = 30, gender = "male", weight = 77.2f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.50f },
                new () { age = 33, gender = "female", weight = 63.0f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 4.90f },
                new () { age = 48, gender = "male", weight = 91.1f, bloodPressure = 145, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 7.50f },
                new () { age = 61, gender = "female", weight = 92.3f, bloodPressure = 155, cholesterolLevel = 225, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 9.70f },
                new () { age = 47, gender = "male", weight = 85.4f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.60f },
                new () { age = 37, gender = "female", weight = 70.1f, bloodPressure = 120, cholesterolLevel = 145, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.30f },
                new () { age = 42, gender = "male", weight = 82.9f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.00f },
                new () { age = 29, gender = "female", weight = 61.5f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.00f },
                new () { age = 50, gender = "male", weight = 80.5f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.90f },
                new () { age = 34, gender = "female", weight = 69.0f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.10f },
                new () { age = 44, gender = "male", weight = 84.2f, bloodPressure = 140, cholesterolLevel = 190, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 3, risk = 7.30f },
                new () { age = 55, gender = "female", weight = 78.4f, bloodPressure = 150, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 7.60f },
                new () { age = 49, gender = "male", weight = 90.7f, bloodPressure = 155, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 8.40f },
                new () { age = 63, gender = "female", weight = 93.5f, bloodPressure = 160, cholesterolLevel = 230, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 9.80f },
                new () { age = 31, gender = "male", weight = 74.3f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.20f },
                new () { age = 46, gender = "female", weight = 79.7f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.40f },
                new () { age = 38, gender = "male", weight = 82.3f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.90f },
                new () { age = 40, gender = "female", weight = 72.0f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.90f },
                new () { age = 52, gender = "male", weight = 88.2f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.80f },
                new () { age = 45, gender = "female", weight = 77.9f, bloodPressure = 140, cholesterolLevel = 210, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 7.50f },
                new () { age = 39, gender = "male", weight = 86.0f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.80f },
                new () { age = 57, gender = "female", weight = 81.1f, bloodPressure = 150, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 8.50f },
                new () { age = 48, gender = "male", weight = 93.0f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 5, risk = 8.00f },
                new () { age = 60, gender = "female", weight = 79.0f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 7.20f },
                new () { age = 32, gender = "male", weight = 77.3f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.20f },
                new () { age = 41, gender = "female", weight = 68.2f, bloodPressure = 125, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.40f },
                new () { age = 35, gender = "male", weight = 79.0f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.50f },

                new () { age = 23, gender = "female", weight = 54.7f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.90f },
                    new () { age = 31, gender = "male", weight = 79.5f, bloodPressure = 135, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.80f },
                    new () { age = 25, gender = "female", weight = 65.3f, bloodPressure = 115, cholesterolLevel = 145, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.60f },
                    new () { age = 36, gender = "male", weight = 90.2f, bloodPressure = 140, cholesterolLevel = 185, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.70f },
                    new () { age = 40, gender = "female", weight = 75.4f, bloodPressure = 130, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.20f },
                    new () { age = 50, gender = "male", weight = 85.1f, bloodPressure = 145, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.70f },
                    new () { age = 27, gender = "female", weight = 63.5f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.10f },
                    new () { age = 38, gender = "male", weight = 82.4f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.10f },
                    new () { age = 48, gender = "female", weight = 77.8f, bloodPressure = 140, cholesterolLevel = 185, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.40f },
                    new () { age = 33, gender = "male", weight = 80.6f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 5.30f },
                    new () { age = 29, gender = "female", weight = 70.4f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.00f },
                    new () { age = 55, gender = "male", weight = 92.1f, bloodPressure = 150, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.80f },
                    new () { age = 39, gender = "female", weight = 74.3f, bloodPressure = 130, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.80f },
                    new () { age = 42, gender = "male", weight = 88.7f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.90f },
                    new () { age = 60, gender = "female", weight = 82.0f, bloodPressure = 155, cholesterolLevel = 225, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 4, risk = 8.70f },
                    new () { age = 43, gender = "male", weight = 87.2f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 7.30f },
                    new () { age = 28, gender = "female", weight = 64.5f, bloodPressure = 125, cholesterolLevel = 155, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 1, risk = 5.10f },
                    new () { age = 47, gender = "male", weight = 83.0f, bloodPressure = 145, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.60f },
                    new () { age = 56, gender = "female", weight = 79.3f, bloodPressure = 150, cholesterolLevel = 205, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 8.00f },
                    new () { age = 41, gender = "male", weight = 80.0f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.50f },
                    new () { age = 35, gender = "female", weight = 70.8f, bloodPressure = 125, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.20f },
                    new () { age = 49, gender = "male", weight = 90.4f, bloodPressure = 145, cholesterolLevel = 215, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.40f },
                    new () { age = 63, gender = "female", weight = 95.1f, bloodPressure = 155, cholesterolLevel = 230, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 9.90f },
                    new () { age = 52, gender = "male", weight = 89.2f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 8.20f },
                    new () { age = 34, gender = "female", weight = 69.1f, bloodPressure = 130, cholesterolLevel = 165, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.10f },
                    new () { age = 61, gender = "male", weight = 91.5f, bloodPressure = 160, cholesterolLevel = 240, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 9.80f },
                    new () { age = 29, gender = "female", weight = 62.0f, bloodPressure = 125, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.90f },
                    new () { age = 36, gender = "male", weight = 82.8f, bloodPressure = 135, cholesterolLevel = 185, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.50f },
                    new () { age = 55, gender = "female", weight = 77.0f, bloodPressure = 145, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 8.10f },
                    new () { age = 40, gender = "male", weight = 85.3f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 2, risk = 6.40f },
                    new () { age = 60, gender = "female", weight = 90.0f, bloodPressure = 150, cholesterolLevel = 230, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 4, risk = 9.60f },
                    new () { age = 45, gender = "male", weight = 88.4f, bloodPressure = 140, cholesterolLevel = 195, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.50f },
                    new () { age = 50, gender = "female", weight = 75.2f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.10f },
                    new () { age = 39, gender = "male", weight = 82.0f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.80f },
                    new () { age = 47, gender = "female", weight = 79.9f, bloodPressure = 140, cholesterolLevel = 195, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.60f },
                    new () { age = 43, gender = "male", weight = 85.2f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.20f },
                    new () { age = 51, gender = "female", weight = 78.0f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 8.30f },
                    new () { age = 29, gender = "male", weight = 81.5f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 2, risk = 6.60f },
                    new () { age = 48, gender = "female", weight = 74.8f, bloodPressure = 125, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 5.00f },
                    new () { age = 53, gender = "male", weight = 95.6f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 5, risk = 8.50f },
                    new () { age = 44, gender = "female", weight = 69.4f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.30f },
                    new () { age = 41, gender = "male", weight = 86.7f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.80f },
                    new () { age = 49, gender = "female", weight = 80.2f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.40f },
                    new () { age = 62, gender = "male", weight = 93.4f, bloodPressure = 155, cholesterolLevel = 235, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 9.40f },
                    new () { age = 29, gender = "female", weight = 66.7f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.20f },
                    new () { age = 50, gender = "male", weight = 92.5f, bloodPressure = 140, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 8.20f },
                    new () { age = 57, gender = "female", weight = 85.1f, bloodPressure = 150, cholesterolLevel = 215, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 8.60f },
                    new () { age = 39, gender = "male", weight = 78.4f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.70f },
                    new () { age = 46, gender = "female", weight = 82.9f, bloodPressure = 140, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.90f },
                    new () { age = 40, gender = "male", weight = 89.3f, bloodPressure = 145, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 7.10f },
                    new () { age = 53, gender = "female", weight = 88.4f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.70f },
                    new () { age = 28, gender = "male", weight = 74.3f, bloodPressure = 120, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.00f },
                    new () { age = 37, gender = "female", weight = 77.1f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.80f },
                    new () { age = 51, gender = "male", weight = 85.6f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.70f },

                    new () { age = 30, gender = "female", weight = 68.5f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.10f },
                new () { age = 40, gender = "male", weight = 78.2f, bloodPressure = 135, cholesterolLevel = 175, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 6.80f },
                new () { age = 34, gender = "female", weight = 70.4f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 5.30f },
                new () { age = 50, gender = "male", weight = 92.0f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.90f },
                new () { age = 29, gender = "female", weight = 58.3f, bloodPressure = 110, cholesterolLevel = 140, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 1, risk = 4.80f },
                new () { age = 38, gender = "male", weight = 80.2f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 6.90f },
                new () { age = 46, gender = "female", weight = 74.1f, bloodPressure = 130, cholesterolLevel = 200, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 7.20f },
                new () { age = 41, gender = "male", weight = 89.5f, bloodPressure = 140, cholesterolLevel = 205, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.80f },
                new () { age = 56, gender = "female", weight = 80.9f, bloodPressure = 150, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 8.10f },
                new () { age = 32, gender = "male", weight = 81.4f, bloodPressure = 120, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.50f },
                new () { age = 50, gender = "female", weight = 85.3f, bloodPressure = 140, cholesterolLevel = 190, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.60f },
                new () { age = 47, gender = "male", weight = 90.1f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 7.50f },
                new () { age = 38, gender = "female", weight = 72.2f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.90f },
                new () { age = 43, gender = "male", weight = 88.9f, bloodPressure = 145, cholesterolLevel = 195, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.80f },
                new () { age = 54, gender = "female", weight = 80.5f, bloodPressure = 155, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 8.40f },
                new () { age = 27, gender = "male", weight = 74.6f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.00f },
                new () { age = 51, gender = "female", weight = 78.9f, bloodPressure = 140, cholesterolLevel = 205, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 7.30f },
                new () { age = 48, gender = "male", weight = 92.4f, bloodPressure = 150, cholesterolLevel = 230, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 8.10f },
                new () { age = 41, gender = "female", weight = 79.2f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 7.00f },
                new () { age = 36, gender = "male", weight = 86.0f, bloodPressure = 135, cholesterolLevel = 185, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.80f },
                new () { age = 42, gender = "female", weight = 83.1f, bloodPressure = 140, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 5, risk = 7.80f },
                new () { age = 34, gender = "male", weight = 76.7f, bloodPressure = 120, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 5.40f },
                new () { age = 39, gender = "female", weight = 80.0f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 6.50f },
                new () { age = 45, gender = "male", weight = 84.8f, bloodPressure = 140, cholesterolLevel = 190, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.20f },
                new () { age = 53, gender = "female", weight = 90.3f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 5, risk = 8.50f },
                new () { age = 49, gender = "male", weight = 87.4f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.60f },
                new () { age = 31, gender = "female", weight = 69.8f, bloodPressure = 120, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.30f },
                new () { age = 50, gender = "male", weight = 88.2f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 5, risk = 7.90f },
                new () { age = 42, gender = "female", weight = 75.0f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 4, risk = 5.70f },
                new () { age = 47, gender = "male", weight = 93.6f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.40f },
                new () { age = 56, gender = "female", weight = 86.3f, bloodPressure = 150, cholesterolLevel = 215, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 5, risk = 8.60f },
                new () { age = 36, gender = "male", weight = 78.4f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 3, risk = 6.50f },
                new () { age = 40, gender = "female", weight = 79.9f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 4, risk = 6.90f },
                new () { age = 34, gender = "male", weight = 85.0f, bloodPressure = 125, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 2, risk = 6.30f },
                new () { age = 49, gender = "female", weight = 92.1f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.20f },
                new () { age = 51, gender = "male", weight = 89.7f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.90f },
                new () { age = 33, gender = "female", weight = 74.3f, bloodPressure = 120, cholesterolLevel = 160, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 2, risk = 5.20f },
                new () { age = 48, gender = "male", weight = 90.7f, bloodPressure = 140, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.60f },
                new () { age = 55, gender = "female", weight = 78.5f, bloodPressure = 150, cholesterolLevel = 215, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 8.70f },
                new () { age = 32, gender = "male", weight = 75.6f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.40f },
                new () { age = 45, gender = "female", weight = 80.2f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 7.10f },
                new () { age = 39, gender = "male", weight = 88.3f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.90f },
                new () { age = 47, gender = "female", weight = 91.5f, bloodPressure = 145, cholesterolLevel = 220, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 7.60f },
                new () { age = 34, gender = "male", weight = 84.2f, bloodPressure = 130, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 2, risk = 6.80f },
                new () { age = 44, gender = "female", weight = 77.9f, bloodPressure = 125, cholesterolLevel = 165, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 5.80f },
                new () { age = 50, gender = "male", weight = 86.1f, bloodPressure = 135, cholesterolLevel = 185, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.90f },
                new () { age = 52, gender = "female", weight = 81.2f, bloodPressure = 140, cholesterolLevel = 205, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.80f },
                new () { age = 39, gender = "male", weight = 80.8f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.50f },

                new () { age = 26, gender = "female", weight = 68.5f, bloodPressure = 120, cholesterolLevel = 145, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.90f },
                new () { age = 39, gender = "male", weight = 82.3f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.20f },
                new () { age = 55, gender = "female", weight = 90.1f, bloodPressure = 145, cholesterolLevel = 205, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.80f },
                new () { age = 33, gender = "male", weight = 76.4f, bloodPressure = 120, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.10f },
                new () { age = 40, gender = "female", weight = 70.5f, bloodPressure = 125, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 4, risk = 6.50f },
                new () { age = 47, gender = "male", weight = 94.2f, bloodPressure = 140, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 7.60f },
                new () { age = 29, gender = "female", weight = 69.0f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 6.00f },
                new () { age = 52, gender = "male", weight = 88.5f, bloodPressure = 145, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.30f },
                new () { age = 28, gender = "female", weight = 72.4f, bloodPressure = 125, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 5.20f },
                new () { age = 38, gender = "male", weight = 81.2f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 2, risk = 6.70f },
                new () { age = 45, gender = "female", weight = 76.9f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 5.90f },
                new () { age = 56, gender = "male", weight = 92.3f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.90f },
                new () { age = 43, gender = "female", weight = 68.1f, bloodPressure = 120, cholesterolLevel = 145, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 4.80f },
                new () { age = 60, gender = "male", weight = 95.4f, bloodPressure = 155, cholesterolLevel = 230, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 9.50f },
                new () { age = 31, gender = "female", weight = 75.0f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.10f },
                new () { age = 58, gender = "male", weight = 90.9f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.80f },
                new () { age = 36, gender = "female", weight = 79.3f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.50f },
                new () { age = 49, gender = "male", weight = 92.6f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 8.10f },
                new () { age = 35, gender = "female", weight = 70.9f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 2, risk = 5.30f },
                new () { age = 60, gender = "male", weight = 89.8f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 8.70f },
                new () { age = 32, gender = "female", weight = 67.2f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.00f },
                new () { age = 48, gender = "male", weight = 84.5f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 6.40f },
                new () { age = 41, gender = "female", weight = 75.6f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.20f },
                new () { age = 50, gender = "male", weight = 91.2f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.90f },
                new () { age = 36, gender = "female", weight = 72.3f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.60f },
                new () { age = 59, gender = "male", weight = 88.6f, bloodPressure = 150, cholesterolLevel = 215, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 8.50f },
                new () { age = 29, gender = "female", weight = 70.4f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 3, risk = 5.00f },
                new () { age = 52, gender = "male", weight = 84.8f, bloodPressure = 135, cholesterolLevel = 195, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.80f },
                new () { age = 41, gender = "female", weight = 74.0f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.60f },
                new () { age = 33, gender = "male", weight = 80.3f, bloodPressure = 140, cholesterolLevel = 195, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 7.10f },
                new () { age = 48, gender = "female", weight = 77.8f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.40f },
                new () { age = 60, gender = "male", weight = 92.4f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 8.60f },
                new () { age = 42, gender = "female", weight = 69.3f, bloodPressure = 135, cholesterolLevel = 185, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 6.50f },
                new () { age = 31, gender = "male", weight = 75.9f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.30f },
                new () { age = 46, gender = "female", weight = 79.4f, bloodPressure = 125, cholesterolLevel = 170, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.80f },
                new () { age = 50, gender = "male", weight = 85.6f, bloodPressure = 135, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 4, risk = 7.00f },
                new () { age = 35, gender = "female", weight = 72.1f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.60f },
                new () { age = 38, gender = "male", weight = 80.7f, bloodPressure = 140, cholesterolLevel = 195, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.20f },
                new () { age = 49, gender = "female", weight = 82.4f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.90f },
                new () { age = 55, gender = "male", weight = 87.2f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 8.40f },
                new () { age = 44, gender = "female", weight = 73.6f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.10f },
                new () { age = 47, gender = "male", weight = 85.3f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.30f },
                new () { age = 34, gender = "female", weight = 71.9f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 6.00f },
                new () { age = 58, gender = "male", weight = 90.2f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 8.80f },
                new () { age = 30, gender = "female", weight = 69.2f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 3, risk = 5.40f },
                new () { age = 49, gender = "male", weight = 83.7f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.00f },
                new () { age = 42, gender = "female", weight = 76.3f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.80f },
                new () { age = 39, gender = "male", weight = 79.8f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 3, risk = 6.20f },

                new () { age = 27, gender = "female", weight = 70.2f, bloodPressure = 130, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.40f },
                new () { age = 35, gender = "male", weight = 82.1f, bloodPressure = 140, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.10f },
                new () { age = 43, gender = "female", weight = 77.5f, bloodPressure = 125, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.60f },
                new () { age = 51, gender = "male", weight = 88.0f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.30f },
                new () { age = 29, gender = "female", weight = 70.8f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.00f },
                new () { age = 37, gender = "male", weight = 85.6f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.40f },
                new () { age = 62, gender = "female", weight = 90.4f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.90f },
                new () { age = 32, gender = "male", weight = 77.3f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.00f },
                new () { age = 45, gender = "female", weight = 73.8f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 5.50f },
                new () { age = 50, gender = "male", weight = 92.0f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.60f },
                new () { age = 41, gender = "female", weight = 74.2f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.80f },
                new () { age = 30, gender = "male", weight = 76.8f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 3, risk = 5.30f },
                new () { age = 47, gender = "female", weight = 79.4f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.30f },
                new () { age = 34, gender = "male", weight = 78.2f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.90f },
                new () { age = 56, gender = "female", weight = 90.6f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 8.40f },
                new () { age = 40, gender = "male", weight = 84.5f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.70f },
                new () { age = 39, gender = "female", weight = 76.9f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.20f },
                new () { age = 28, gender = "male", weight = 74.4f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 3, risk = 5.50f },
                new () { age = 53, gender = "female", weight = 89.2f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 8.20f },
                new () { age = 33, gender = "male", weight = 75.3f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.10f },
                new () { age = 48, gender = "female", weight = 80.4f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.40f },
                new () { age = 57, gender = "male", weight = 91.5f, bloodPressure = 145, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.70f },
                new () { age = 29, gender = "female", weight = 70.1f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 2, risk = 5.00f },
                new () { age = 44, gender = "male", weight = 84.9f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.00f },
                new () { age = 55, gender = "female", weight = 90.3f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.50f },
                new () { age = 41, gender = "male", weight = 76.7f, bloodPressure = 135, cholesterolLevel = 185, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.00f },
                new () { age = 50, gender = "female", weight = 82.2f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.10f },
                new () { age = 60, gender = "male", weight = 92.5f, bloodPressure = 150, cholesterolLevel = 230, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 9.00f },
                new () { age = 32, gender = "female", weight = 75.0f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.40f },
                new () { age = 37, gender = "male", weight = 83.6f, bloodPressure = 140, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.60f },
                new () { age = 42, gender = "female", weight = 77.0f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 4, risk = 7.20f },
                new () { age = 30, gender = "male", weight = 76.1f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 5.30f },
                new () { age = 46, gender = "female", weight = 80.9f, bloodPressure = 125, cholesterolLevel = 165, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.20f },
                new () { age = 54, gender = "male", weight = 89.3f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.90f },
                new () { age = 39, gender = "female", weight = 76.5f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.50f },
                new () { age = 29, gender = "male", weight = 78.0f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.80f },
                new () { age = 35, gender = "female", weight = 81.3f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.10f },
                new () { age = 40, gender = "male", weight = 85.0f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 6.80f },
                new () { age = 32, gender = "female", weight = 73.5f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.30f },
                new () { age = 45, gender = "male", weight = 80.0f, bloodPressure = 140, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.10f },
                new () { age = 29, gender = "female", weight = 68.3f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.00f },
                new () { age = 55, gender = "male", weight = 91.2f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.40f },
                new () { age = 38, gender = "female", weight = 77.9f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 5.90f },
                new () { age = 49, gender = "male", weight = 90.2f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.70f },
                new () { age = 31, gender = "female", weight = 73.2f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.40f },

                new () { age = 26, gender = "male", weight = 72.3f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.80f },
                new () { age = 52, gender = "female", weight = 84.6f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.30f },
                new () { age = 33, gender = "male", weight = 78.2f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.90f },
                new () { age = 48, gender = "female", weight = 80.0f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.80f },
                new () { age = 41, gender = "male", weight = 87.4f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.20f },
                new () { age = 39, gender = "female", weight = 75.3f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 3, risk = 5.60f },
                new () { age = 63, gender = "male", weight = 93.1f, bloodPressure = 145, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.90f },
                new () { age = 36, gender = "female", weight = 71.2f, bloodPressure = 130, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.50f },
                new () { age = 31, gender = "male", weight = 76.8f, bloodPressure = 125, cholesterolLevel = 170, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 3, risk = 5.80f },
                new () { age = 58, gender = "female", weight = 85.5f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 7.90f },
                new () { age = 44, gender = "male", weight = 84.0f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 6.50f },
                new () { age = 49, gender = "female", weight = 82.3f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.90f },
                new () { age = 61, gender = "male", weight = 91.7f, bloodPressure = 150, cholesterolLevel = 230, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.80f },
                new () { age = 26, gender = "female", weight = 69.4f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.10f },
                new () { age = 38, gender = "male", weight = 81.2f, bloodPressure = 125, cholesterolLevel = 170, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 3, risk = 6.00f },
                new () { age = 34, gender = "female", weight = 75.6f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.70f },
                new () { age = 46, gender = "male", weight = 86.4f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.20f },
                new () { age = 30, gender = "female", weight = 72.1f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.00f },
                new () { age = 55, gender = "male", weight = 90.3f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.70f },
                new () { age = 42, gender = "female", weight = 79.5f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.10f },
                new () { age = 59, gender = "male", weight = 94.0f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 9.00f },
                new () { age = 36, gender = "female", weight = 74.2f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.00f },
                new () { age = 40, gender = "male", weight = 78.3f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.90f },
                new () { age = 27, gender = "female", weight = 69.2f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.10f },
                new () { age = 62, gender = "male", weight = 92.8f, bloodPressure = 145, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.80f },
                new () { age = 33, gender = "female", weight = 73.4f, bloodPressure = 130, cholesterolLevel = 165, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.50f },
                new () { age = 49, gender = "male", weight = 85.7f, bloodPressure = 135, cholesterolLevel = 185, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.30f },
                new () { age = 38, gender = "female", weight = 77.8f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.60f },
                new () { age = 29, gender = "male", weight = 75.2f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 5.70f },
                new () { age = 41, gender = "female", weight = 80.1f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.20f },
                new () { age = 52, gender = "male", weight = 90.0f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.50f },
                new () { age = 50, gender = "female", weight = 81.2f, bloodPressure = 135, cholesterolLevel = 185, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 6.80f },
                new () { age = 35, gender = "male", weight = 80.8f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 6.40f },
                new () { age = 59, gender = "female", weight = 92.1f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.90f },
                new () { age = 28, gender = "male", weight = 73.9f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 5.10f },
                new () { age = 33, gender = "female", weight = 78.0f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 5.90f },
                new () { age = 49, gender = "male", weight = 85.3f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 6.80f },
                new () { age = 30, gender = "female", weight = 71.1f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.60f },
                new () { age = 41, gender = "male", weight = 82.4f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.70f },

                new () { age = 25, gender = "female", weight = 60.3f, bloodPressure = 118, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.50f },
new () { age = 31, gender = "male", weight = 77.8f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 6.10f },
new () { age = 48, gender = "female", weight = 85.4f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 4, risk = 6.80f },
new () { age = 60, gender = "male", weight = 92.2f, bloodPressure = 145, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.90f },
new () { age = 28, gender = "female", weight = 70.1f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.40f },
new () { age = 52, gender = "male", weight = 88.9f, bloodPressure = 140, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.20f },
new () { age = 35, gender = "female", weight = 73.3f, bloodPressure = 125, cholesterolLevel = 165, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 5.90f },
new () { age = 40, gender = "male", weight = 80.4f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 2, risk = 6.30f },
new () { age = 45, gender = "female", weight = 82.0f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.50f },
new () { age = 33, gender = "male", weight = 76.2f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 2, risk = 5.10f },
new () { age = 58, gender = "female", weight = 89.4f, bloodPressure = 145, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.80f },
new () { age = 50, gender = "male", weight = 86.5f, bloodPressure = 140, cholesterolLevel = 210, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 7.10f },
new () { age = 22, gender = "female", weight = 65.1f, bloodPressure = 120, cholesterolLevel = 140, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.30f },
new () { age = 36, gender = "male", weight = 78.7f, bloodPressure = 128, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.60f },
new () { age = 42, gender = "female", weight = 80.3f, bloodPressure = 133, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.90f },
new () { age = 37, gender = "male", weight = 82.8f, bloodPressure = 126, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.80f },
new () { age = 61, gender = "female", weight = 90.5f, bloodPressure = 145, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.60f },
new () { age = 30, gender = "male", weight = 77.5f, bloodPressure = 120, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 5.30f },
new () { age = 47, gender = "female", weight = 83.2f, bloodPressure = 138, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.00f },
new () { age = 53, gender = "male", weight = 91.0f, bloodPressure = 140, cholesterolLevel = 205, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 3, risk = 7.50f },
new () { age = 32, gender = "female", weight = 72.5f, bloodPressure = 124, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 5.00f },
new () { age = 56, gender = "male", weight = 94.0f, bloodPressure = 145, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.40f },
new () { age = 24, gender = "female", weight = 68.6f, bloodPressure = 120, cholesterolLevel = 145, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.60f },
new () { age = 38, gender = "male", weight = 81.5f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 6.40f },
new () { age = 29, gender = "female", weight = 74.3f, bloodPressure = 122, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.80f },
new () { age = 51, gender = "male", weight = 89.2f, bloodPressure = 138, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.20f },
new () { age = 44, gender = "female", weight = 81.4f, bloodPressure = 134, cholesterolLevel = 185, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.30f },
new () { age = 39, gender = "male", weight = 80.9f, bloodPressure = 125, cholesterolLevel = 165, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.90f },
new () { age = 28, gender = "female", weight = 69.8f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 1f, stressLevel = 2, risk = 5.00f },
new () { age = 45, gender = "male", weight = 87.1f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 7.30f },
new () { age = 41, gender = "female", weight = 79.2f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.10f },
new () { age = 33, gender = "male", weight = 75.4f, bloodPressure = 122, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 5.40f },
new () { age = 55, gender = "female", weight = 90.6f, bloodPressure = 140, cholesterolLevel = 205, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.50f },
new () { age = 60, gender = "male", weight = 93.7f, bloodPressure = 145, cholesterolLevel = 215, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 8.60f },
new () { age = 26, gender = "female", weight = 71.2f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.90f },
new () { age = 34, gender = "male", weight = 78.0f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.10f },
new () { age = 49, gender = "female", weight = 84.5f, bloodPressure = 137, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 6.90f },
new () { age = 52, gender = "male", weight = 90.1f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.30f },
new () { age = 46, gender = "female", weight = 81.0f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.00f },

new () { age = 30, gender = "female", weight = 62.4f, bloodPressure = 118, cholesterolLevel = 150, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 4.80f },
new () { age = 40, gender = "male", weight = 85.2f, bloodPressure = 125, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 5.90f },
new () { age = 53, gender = "female", weight = 77.9f, bloodPressure = 138, cholesterolLevel = 190, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 6.80f },
new () { age = 61, gender = "male", weight = 89.5f, bloodPressure = 142, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.60f },
new () { age = 28, gender = "female", weight = 70.1f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.50f },
new () { age = 45, gender = "male", weight = 91.8f, bloodPressure = 135, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 6.50f },
new () { age = 39, gender = "female", weight = 78.3f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 5.70f },
new () { age = 48, gender = "male", weight = 82.0f, bloodPressure = 135, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.10f },
new () { age = 34, gender = "female", weight = 75.5f, bloodPressure = 125, cholesterolLevel = 165, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 5.10f },
new () { age = 58, gender = "male", weight = 93.6f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.20f },
new () { age = 22, gender = "female", weight = 63.8f, bloodPressure = 118, cholesterolLevel = 140, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.00f },
new () { age = 32, gender = "male", weight = 79.7f, bloodPressure = 125, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 2, risk = 5.80f },
new () { age = 49, gender = "female", weight = 84.3f, bloodPressure = 132, cholesterolLevel = 185, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 4, risk = 6.70f },
new () { age = 55, gender = "male", weight = 87.2f, bloodPressure = 138, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 3, risk = 7.40f },
new () { age = 60, gender = "female", weight = 91.0f, bloodPressure = 145, cholesterolLevel = 215, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 5, risk = 8.50f },
new () { age = 27, gender = "male", weight = 75.3f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.40f },
new () { age = 41, gender = "female", weight = 80.6f, bloodPressure = 128, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.90f },
new () { age = 38, gender = "male", weight = 82.9f, bloodPressure = 135, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.20f },
new () { age = 52, gender = "female", weight = 79.8f, bloodPressure = 128, cholesterolLevel = 160, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.00f },
new () { age = 33, gender = "male", weight = 74.4f, bloodPressure = 122, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 5.00f },
new () { age = 30, gender = "female", weight = 70.2f, bloodPressure = 118, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.60f },
new () { age = 51, gender = "male", weight = 88.6f, bloodPressure = 130, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 6.80f },
new () { age = 29, gender = "female", weight = 73.4f, bloodPressure = 120, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.30f },
new () { age = 44, gender = "male", weight = 86.7f, bloodPressure = 137, cholesterolLevel = 195, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.90f },
new () { age = 50, gender = "female", weight = 80.5f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 6.10f },
new () { age = 57, gender = "male", weight = 92.3f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.60f },
new () { age = 26, gender = "female", weight = 69.7f, bloodPressure = 115, cholesterolLevel = 140, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.10f },
new () { age = 36, gender = "male", weight = 76.0f, bloodPressure = 124, cholesterolLevel = 165, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.20f },
new () { age = 43, gender = "female", weight = 80.1f, bloodPressure = 128, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.30f },
new () { age = 49, gender = "male", weight = 85.4f, bloodPressure = 134, cholesterolLevel = 185, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 3, risk = 6.50f },
new () { age = 54, gender = "female", weight = 86.9f, bloodPressure = 140, cholesterolLevel = 190, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.00f },
new () { age = 35, gender = "male", weight = 77.0f, bloodPressure = 126, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.80f },
new () { age = 60, gender = "female", weight = 88.2f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 7.90f },
new () { age = 41, gender = "male", weight = 81.0f, bloodPressure = 130, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.10f },
new () { age = 31, gender = "female", weight = 70.0f, bloodPressure = 122, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.50f },
new () { age = 48, gender = "male", weight = 87.0f, bloodPressure = 135, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 7.00f },
new () { age = 29, gender = "female", weight = 74.5f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.30f },
new () { age = 50, gender = "male", weight = 88.1f, bloodPressure = 134, cholesterolLevel = 180, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 6.90f },
new () { age = 42, gender = "female", weight = 78.2f, bloodPressure = 126, cholesterolLevel = 165, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 5.60f },
new () { age = 61, gender = "male", weight = 91.7f, bloodPressure = 142, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.80f },
new () { age = 37, gender = "female", weight = 72.6f, bloodPressure = 118, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 5.10f },
new () { age = 47, gender = "male", weight = 85.2f, bloodPressure = 133, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.80f },
new () { age = 28, gender = "female", weight = 69.4f, bloodPressure = 120, cholesterolLevel = 145, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 4.40f },
new () { age = 39, gender = "male", weight = 80.3f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 6.20f },
new () { age = 30, gender = "female", weight = 68.7f, bloodPressure = 125, cholesterolLevel = 155, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 2, risk = 5.40f },
new () { age = 33, gender = "male", weight = 74.1f, bloodPressure = 122, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.00f },
new () { age = 44, gender = "female", weight = 76.2f, bloodPressure = 130, cholesterolLevel = 170, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 5.80f },
new () { age = 52, gender = "male", weight = 89.8f, bloodPressure = 140, cholesterolLevel = 195, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.10f },
new () { age = 55, gender = "female", weight = 80.5f, bloodPressure = 132, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 6.00f },
new () { age = 56, gender = "male", weight = 92.3f, bloodPressure = 148, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.90f },
new () { age = 29, gender = "female", weight = 73.0f, bloodPressure = 119, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.20f },
new () { age = 40, gender = "male", weight = 78.5f, bloodPressure = 126, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.40f },
new () { age = 48, gender = "female", weight = 79.2f, bloodPressure = 128, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.50f },
new () { age = 53, gender = "male", weight = 83.3f, bloodPressure = 132, cholesterolLevel = 190, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 6.80f },
new () { age = 60, gender = "female", weight = 84.0f, bloodPressure = 136, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 5, risk = 7.50f },
new () { age = 34, gender = "male", weight = 75.0f, bloodPressure = 120, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 5.20f },
new () { age = 62, gender = "female", weight = 89.7f, bloodPressure = 140, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.90f },
new () { age = 49, gender = "male", weight = 87.1f, bloodPressure = 128, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 6.30f },
new () { age = 28, gender = "female", weight = 70.0f, bloodPressure = 118, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 4.00f },
new () { age = 31, gender = "male", weight = 79.0f, bloodPressure = 126, cholesterolLevel = 165, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.30f },
new () { age = 54, gender = "female", weight = 83.6f, bloodPressure = 133, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.50f },
new () { age = 32, gender = "male", weight = 76.8f, bloodPressure = 124, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 5.60f },
new () { age = 56, gender = "female", weight = 85.0f, bloodPressure = 137, cholesterolLevel = 195, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.20f },
new () { age = 30, gender = "female", weight = 65.5f, bloodPressure = 118, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.10f },
new () { age = 45, gender = "male", weight = 90.2f, bloodPressure = 135, cholesterolLevel = 175, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.50f },
new () { age = 52, gender = "female", weight = 78.8f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 3, risk = 5.70f },
new () { age = 41, gender = "male", weight = 88.1f, bloodPressure = 140, cholesterolLevel = 190, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.00f },
new () { age = 29, gender = "female", weight = 72.4f, bloodPressure = 120, cholesterolLevel = 160, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 4.30f },
new () { age = 35, gender = "male", weight = 79.8f, bloodPressure = 128, cholesterolLevel = 165, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.40f },
new () { age = 47, gender = "female", weight = 83.5f, bloodPressure = 135, cholesterolLevel = 185, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.90f },
new () { age = 54, gender = "male", weight = 86.3f, bloodPressure = 142, cholesterolLevel = 195, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 7.50f },
new () { age = 40, gender = "female", weight = 76.1f, bloodPressure = 126, cholesterolLevel = 170, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 5.10f },
new () { age = 60, gender = "male", weight = 94.0f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.00f },
new () { age = 38, gender = "female", weight = 71.6f, bloodPressure = 122, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 5.30f },
new () { age = 27, gender = "male", weight = 74.9f, bloodPressure = 118, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.20f },
new () { age = 44, gender = "female", weight = 79.0f, bloodPressure = 133, cholesterolLevel = 170, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 5.80f },
new () { age = 32, gender = "male", weight = 80.3f, bloodPressure = 124, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 5.00f },
new () { age = 51, gender = "female", weight = 85.7f, bloodPressure = 138, cholesterolLevel = 190, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 6.90f },
new () { age = 29, gender = "male", weight = 77.4f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 3, risk = 4.50f },
new () { age = 49, gender = "female", weight = 81.5f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.60f },
new () { age = 33, gender = "male", weight = 73.2f, bloodPressure = 119, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 4.00f },
new () { age = 46, gender = "female", weight = 89.1f, bloodPressure = 140, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.80f },
new () { age = 58, gender = "male", weight = 92.4f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.10f },
new () { age = 37, gender = "female", weight = 75.3f, bloodPressure = 123, cholesterolLevel = 165, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.90f },
new () { age = 40, gender = "male", weight = 80.7f, bloodPressure = 127, cholesterolLevel = 175, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 5.80f },
new () { age = 62, gender = "female", weight = 86.5f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 8.30f },
new () { age = 28, gender = "male", weight = 74.0f, bloodPressure = 119, cholesterolLevel = 150, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.00f },
new () { age = 39, gender = "female", weight = 82.0f, bloodPressure = 132, cholesterolLevel = 178, physicalActivityLevel = 2, smokingStatus = 1f, stressLevel = 4, risk = 6.40f },
new () { age = 44, gender = "male", weight = 89.5f, bloodPressure = 138, cholesterolLevel = 182, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 5, risk = 6.70f },
new () { age = 29, gender = "female", weight = 70.2f, bloodPressure = 118, cholesterolLevel = 150, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 4.60f },
new () { age = 41, gender = "male", weight = 77.0f, bloodPressure = 124, cholesterolLevel = 160, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.90f },
new () { age = 53, gender = "female", weight = 88.7f, bloodPressure = 145, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.80f },
new () { age = 62, gender = "male", weight = 94.0f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 8.10f },
new () { age = 34, gender = "female", weight = 75.5f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 2, risk = 4.30f },
new () { age = 36, gender = "male", weight = 80.2f, bloodPressure = 128, cholesterolLevel = 167, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 4, risk = 5.50f },
new () { age = 59, gender = "female", weight = 82.3f, bloodPressure = 143, cholesterolLevel = 215, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.90f },
new () { age = 48, gender = "male", weight = 84.1f, bloodPressure = 137, cholesterolLevel = 200, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 6.30f },
new () { age = 50, gender = "female", weight = 85.2f, bloodPressure = 141, cholesterolLevel = 210, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.50f },
new () { age = 60, gender = "male", weight = 90.4f, bloodPressure = 146, cholesterolLevel = 225, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 8.00f },
new () { age = 45, gender = "female", weight = 80.0f, bloodPressure = 130, cholesterolLevel = 180, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 6.10f },
new () { age = 33, gender = "male", weight = 78.0f, bloodPressure = 124, cholesterolLevel = 155, physicalActivityLevel = 3, smokingStatus = 1f, stressLevel = 3, risk = 5.10f },
new () { age = 28, gender = "female", weight = 70.8f, bloodPressure = 118, cholesterolLevel = 148, physicalActivityLevel = 3, smokingStatus = 0f, stressLevel = 2, risk = 4.00f },
new () { age = 57, gender = "male", weight = 93.5f, bloodPressure = 142, cholesterolLevel = 215, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 4, risk = 7.70f },
new () { age = 49, gender = "female", weight = 85.9f, bloodPressure = 138, cholesterolLevel = 190, physicalActivityLevel = 2, smokingStatus = 0f, stressLevel = 4, risk = 6.50f },
new () { age = 56, gender = "male", weight = 88.9f, bloodPressure = 141, cholesterolLevel = 200, physicalActivityLevel = 1, smokingStatus = 1f, stressLevel = 5, risk = 7.80f },
new () { age = 35, gender = "female", weight = 74.3f, bloodPressure = 120, cholesterolLevel = 155, physicalActivityLevel = 4, smokingStatus = 0f, stressLevel = 3, risk = 4.60f },
new () { age = 63, gender = "male", weight = 92.0f, bloodPressure = 150, cholesterolLevel = 220, physicalActivityLevel = 1, smokingStatus = 0f, stressLevel = 5, risk = 8.30f }


            };
        }
    }
}